### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by iefserge** [runtimejs/runtime#25]
I'll use this issue as tasks checklist.
Let me know if you want to hack on something from this list or anything else :)

Network stack:

- [ ] Cleanup network stack / architecture
- [x] Basic virtio-net driver
- [ ] Test virtio-net driver under high load
- [ ] Add sent callbacks
- [ ] Ethernet transfer packet queue
- [ ] Routing table, route program
- [x] UDP protocol
- [ ] UDP multicast
- [x] Implement DHCP protocol
- [ ] Zero-copy receive (payload+headers), ArrayBuffer resize
- [ ] Network ARP requests / reply and caching / announce
- [ ] Full IPv4 packet parser
- [ ] Implement TCP protocol
- [ ] Implement ICMP protocol, respond to pings, ping program
- [ ] Define low-level socket API for applications
- [x] Implement DNS client
- [ ] Implement DNS server
- [ ] Implement IPv4 fragmentation / do not fragment
- [ ] Loopback interface
- [ ] Packet statistics

Timers:

- [x] HPET support
- [ ] Clocksource abstraction
- [ ] TSC counter support
- [x] add `performance.now()` https://developer.mozilla.org/en-US/docs/Web/API/Performance.now()
- [x] Better APIC timer calibration (using HPET for example)
- [ ] KVM clock timer using MSR ( http://lwn.net/Articles/389375/ )
- [x] console.time()
- [ ] Kernel benchmarks

Network tools:

- [ ] HTTP protocol
- [ ] Web server
- [ ] Benchmark DNS server under high load

Build system:

- [x] Update Dockerfile script gcc version

Threading:

- [ ] Add native threads support (for v8 worker GC sweeper threads)
- [x] Idle thread should call `asm('hlt')`
- [x] Fix CPU usage on KVM
- [ ] CFS scheduler

Tests:

- [ ] Add test framework

**Comment by iefserge** [comment]
Needs to be updated.

**Comment by aafrey** [comment]
How much of these to-dos are still relevent

**Comment by piranna** [comment]
Native threads is one of them...
